# Generated by Django 5.2 on 2025-04-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addrecipe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cookbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='identifiedby',
            options={},
        ),
        migrations.AlterModelOptions(
            name='includes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
