# Generated by Django 5.2 on 2025-04-21 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_addrecipe_options_alter_admin_options_and_more'),
    ]

    operations = [

	migrations.AlterModelOptions(
            name='addrecipe',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cookbook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='identifiedby',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='admin',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),

    ]
