# Generated by Django 5.2 on 2025-04-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_includes_alter_addrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookbook',
            options={},
        ),
    ]
