# Generated by Django 5.2 on 2025-04-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cookbook_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='num_of_saves',
        ),
        migrations.AlterField(
            model_name='cookbook',
            name='cb_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
