# Generated by Django 5.2 on 2025-04-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cookbook_num_of_saves_alter_cookbook_cb_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookbook',
            options={'managed': False},
        ),
    ]
