# Generated by Django 5.2 on 2025-04-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cookbook_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Includes',
        ),
    ]
