# Generated by Django 5.2 on 2025-04-23 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_includes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedCookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'subscribed_cookbook',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
    ]
